#!/bin/bash
# Script to help set up Grafana dashboard for API metrics

echo "=========================================="
echo "Grafana Dashboard Setup Guide"
echo "=========================================="
echo ""

echo "1. Access Grafana:"
echo "   kubectl port-forward service/grafana-service 3000:3000"
echo "   Open: http://localhost:3000"
echo "   Login: admin / admin"
echo ""

echo "2. Add Prometheus Data Source:"
echo "   - Go to Configuration → Data Sources"
echo "   - Add Prometheus"
echo "   - URL: http://prometheus-service:9090"
echo "   - Save & Test"
echo ""

echo "3. Create Dashboard with these panels:"
echo ""
echo "   Panel 1: Request Rate"
echo "   Query: rate(api_requests_total[5m])"
echo "   Visualization: Time series"
echo ""
echo "   Panel 2: Request Duration (95th percentile)"
echo "   Query: histogram_quantile(0.95, rate(api_request_duration_seconds_bucket[5m]))"
echo "   Visualization: Time series"
echo ""
echo "   Panel 3: Total Predictions"
echo "   Query: predictions_total"
echo "   Visualization: Stat"
echo ""
echo "   Panel 4: Prediction Distribution"
echo "   Query: predictions_total"
echo "   Visualization: Pie chart"
echo ""
echo "   Panel 5: Error Rate"
echo "   Query: rate(api_requests_total{status=~\"5..\"}[5m])"
echo "   Visualization: Time series"
echo ""

echo "4. Generate some test traffic:"
echo "   ./scripts/test_api.sh"
echo ""

echo "=========================================="
echo "Quick Access Commands:"
echo "=========================================="
echo ""
echo "Prometheus: kubectl port-forward service/prometheus-service 9090:9090"
echo "Grafana:   kubectl port-forward service/grafana-service 3000:3000"
echo "API:       kubectl port-forward service/heart-disease-api-service 8000:80"
echo ""

